trigger:
  batch: true

variables:
  # Change the following along with adding new TEST_START_INDEX.
  TEST_COUNT: 21

jobs:
# Mac and Linux use the same template with different matrixes
- template: buildscripts/azure/azure-linux-macos.yml
  parameters:
    name: macOS
    vmImage: macos-11
    matrix:
      py39_np126:
        PYTHON: '3.9'
        NUMPY: '1.26'
        CONDA_ENV: 'azure_ci'
        TEST_START_INDEX: 0
      py311_np126:
        PYTHON: '3.11'
        NUMPY: '1.26'
        CONDA_ENV: 'azure_ci'
        TEST_THREADING: 'tbb'
        TEST_START_INDEX: 1

- template: buildscripts/azure/azure-linux-macos.yml
  parameters:
    name: Linux
    vmImage: ubuntu-20.04
    matrix:
      py39_np126_tbb:
        PYTHON: '3.9'
        NUMPY: '1.26'
        CONDA_ENV: azure_ci
        TEST_THREADING: 'tbb'
        TEST_START_INDEX: 2
      py39_np126_omp:
        PYTHON: '3.9'
        NUMPY: '1.26'
        CONDA_ENV: azure_ci
        TEST_THREADING: omp
        TEST_START_INDEX: 3
      py39_np126_workqueue:
        PYTHON: '3.9'
        NUMPY: '1.26'
        CONDA_ENV: azure_ci
        TEST_THREADING: workqueue
        TEST_START_INDEX: 4
      py39_np126_svml:
        PYTHON: '3.9'
        NUMPY: '1.26'
        CONDA_ENV: azure_ci
        TEST_SVML: yes
        TEST_START_INDEX: 5
      py39_np126:
        PYTHON: '3.9'
        NUMPY: '1.26'
        CONDA_ENV: azure_ci
        TEST_START_INDEX: 6
      py39_np126_cov_doc:
        PYTHON: '3.9'
        NUMPY: '1.26'
        CONDA_ENV: azure_ci
        RUN_COVERAGE: yes
        RUN_FLAKE8: yes
        RUN_MYPY: yes
        BUILD_DOC: yes
        TEST_START_INDEX: 7
      py39_np126_typeguard:
        PYTHON: '3.9'
        NUMPY: '1.26'
        CONDA_ENV: azure_ci
        RUN_TYPEGUARD: yes
        TEST_START_INDEX: 8
      py39_np126_slice_9:
        PYTHON: '3.9'
        NUMPY: '1.26'
        CONDA_ENV: azure_ci
        TEST_START_INDEX: 9
      py39_np126_slice_10:
        PYTHON: '3.9'
        NUMPY: '1.26'
        CONDA_ENV: azure_ci
        TEST_START_INDEX: 10
      py310_np126:
        PYTHON: '3.10'
        NUMPY: '1.26'
        CONDA_ENV: azure_ci
        TEST_START_INDEX: 11
      py310_np126_slice_12:
        PYTHON: '3.10'
        NUMPY: '1.26'
        CONDA_ENV: azure_ci
        TEST_START_INDEX: 12
      py310_np126_slice_13:
        PYTHON: '3.10'
        NUMPY: '1.26'
        CONDA_ENV: azure_ci
        TEST_START_INDEX: 13
      py310_np126_slice_14:
        PYTHON: '3.10'
        NUMPY: '1.26'
        CONDA_ENV: azure_ci
        TEST_START_INDEX: 14
      py311_np126:
        PYTHON: '3.11'
        NUMPY: '1.26'
        CONDA_ENV: azure_ci
        TEST_START_INDEX: 15
      py311_np126_slice_16:
        PYTHON: '3.11'
        NUMPY: '1.26'
        CONDA_ENV: azure_ci
        TEST_START_INDEX: 16
      py311_np126_slice_17:
        PYTHON: '3.11'
        NUMPY: '1.26'
        CONDA_ENV: azure_ci
        TEST_START_INDEX: 17
      # RVSDG tests
      py311_np126_rvsdg:
        PYTHON: '3.11'
        NUMPY: '1.26'
        RUN_MYPY: yes
        RUN_FLAKE8: yes
        CONDA_ENV: azure_ci
        TEST_RVSDG: yes
        TEST_START_INDEX: 20   # Not used by test script

- template: buildscripts/azure/azure-windows.yml
  parameters:
    name: Windows
    vmImage: windows-2019
